#! /bin/sh

# Kill old tasks
pkill picom
pkill pipewire
pkill pipewire-pulse
pkill keepassxc
pkill feh

# Start programs
picom &
feh --bg-fill ~/.dotfiles/wallpaper.png &
pipewire &
pipewire-pulse &
keepassxc &
setxkbmap -layout gb &
setxkbmap -option caps:backspace &

pgrep -x sxhkd > /dev/null || sxhkd &

# Settings
bspc monitor -d TTY DEV FUN DIR WWW VI VII VIII IX X
xsetroot -cursor_name left_ptr # Make sure default cursor is normal

# Window Settings
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color		"#6c7086"
bspc config active_border_color		"#b4befe"
bspc config focused_border_color	"#b4befe"
bspc config presel_feedback_color	"#f9e2af"

# Program settings
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
